### ISSUE TITLE
Classes : static method

### ISSUE THREAD

**Issue by cmatschiner** [cmatschiner/eloquent-javascript-bernhard#1]
https://github.com/cmatschiner/eloquent-javascript-bernhard/blob/fefef8d5c3fb72bf1b413a38b4193062b9141054/src/chapter-6/examples/Temperature.js#L18

Die static method "fromFahrenheit" ist doch völlig unnötig?!!

**Comment by bernharduw** [comment]
Na ja, nicht unbedingt. Du kannst folgendes machen:

```js
let temp = Temperature.fromFahrenheit(71.6);
console.log(temp.celsius); // => 22
```

Du kannst das zwar auch so lösen:
```js
let temp = new Temperature();
temp.fahrenheit = 71.6;
console.log(temp.celsius); // => 22
```

Die erste Variante ist lesbarer, weil die Absicht deutlicher ist. Das ist ein wichtiger Punkt, weil du im Regelfall Code 10x so oft liest wie schreibst.

Solche sogenannten Factory-Methoden sind durchaus gebräuchlich, sogar im JavaScript-Standard ist das für Arrays eingeführt worden (`Array.from(x)`):

https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/from

Das Beispiel mit der Temperatur ist natürlich bewusst einfach gehalten, aber auch in React werden statische Methoden  und Attribute eingesetzt. Hier ein Beispiel: https://github.com/zeit/next.js#fetching-data-and-component-lifecycle und ein Artikel: https://medium.com/front-end-weekly/understanding-static-in-javascript-10782149993

Im Prinzip sind statische Methoden verwendbar, ohne dass du extra eine Klassen-Instanz erzeugen musst. In diesem konkreten Fall ist das Ergebnis eine konkrete Instanz, deswegen ist das verwirrender als nötig. Im Prinzip wäre es auch denkbar, dass du statt einer kompletten Instanz nur den Celsius-Wert zurückgibst, etwa mit einer zusätzlichen statischen Methode:

```js
static celsiusFromFahrenheit(fahrenheit) {
  const temp = new Temperature();
  temp.fahrenheit = fahrenheit;
  return temp.celsius;
  }
```

Dann könntest du diese Methode so aufrufen:

```js
console.log(Temperature.celsiusFromFahrenheit(71.6); // => 22
```

Nicht der effizienteste Code. Aber so musst du dir keine Gedanken machen, ob du eine Instanz erzeugst, ob du sie später wiederverwenden kannst oder besser eine neue Instanz erzeugst etc.

Wenn die Klasse dann eine wesentlich kompliziertere Aufgabe hat, etwa eine Webseite aus verschiedenen Daten zu erzeugen und dazwischen umfangreiche Berechnungen zu machen, dann ergibt das plötzlich mehr Sinn: Die Klasse kann dann alle möglichen Fälle abdecken, aber für die einfachen Standardarbeiten kannst du eine statische Hilfsmethode erstellen, die eine Instanz erzeugt, die häufigsten Werte setzt und dann das Ergebnis zurückgibt, aber den gesamten existierenden Code wiederverwendet.
